version: '3.3'
services:
  postgis:
    build: ./postgis
    ports:
      - 5432:5432
    volumes:  
      - ./postgis/data:/var/lib/postgresql/data/airplanes
  tomcat:
    build: ./tomcat
    ports:
      - 8080:8080
  web:
    build: ./web
    ports:
      - 80:80
