version: '3.3'
services:
  postgis:
    build: ./postgis
    ports:
      - 5433:5432
    volumes:  
      - ./postgis/data:/var/lib/postgresql/data
  tomcat:
    build: ./tomcat
    ports:
      - 8080:8080
    volumes:
      - ./tomcat:/usr/local/tomcat/webapps/
  web:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./web/build:/usr/share/nginx/html
