
-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE "TASA" (
    codigo_tasa bigint PRIMARY KEY,
    importe numeric,
    nombre text
);
-- Indices -------------------------------------------------------
CREATE UNIQUE INDEX "TASA_pkey" ON "TASA"(codigo_tasa int8_ops);




-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE "TIPO_ZONA" (
    codigo_tipo_zona bigint PRIMARY KEY,
    codigo_tasa bigint REFERENCES "TASA"(codigo_tasa),
    nombre text
);
-- Indices -------------------------------------------------------
CREATE UNIQUE INDEX "TIPO_ZONA_pkey" ON "TIPO_ZONA"(codigo_tipo_zona int8_ops);



-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.
-- Table Definition ----------------------------------------------
CREATE TABLE "AREA" (
    codigo_zona bigint PRIMARY KEY,
    codigo_tipo_zona bigint REFERENCES "TIPO_ZONA"(codigo_tipo_zona),
    frontera geometry,
    nombre text
);
-- Indices -------------------------------------------------------
CREATE UNIQUE INDEX "AREA_pkey" ON "AREA"(codigo_zona int8_ops);

